"""Storage port for graph adapters.

The memory architecture is a property graph. The bundled adapter persists graph
records in REQL block files; any backend implementing this protocol can be used
by the services.
"""
from __future__ import annotations

from contextlib import AbstractContextManager
from typing import Any, Protocol, Sequence

from ..domain.models import MemoryEdge, MemoryNode


class GraphStore(Protocol):
    """Port implemented by graph storage adapters."""

    def initialize(self) -> None: ...
    def close(self) -> None: ...
    def transaction(self) -> AbstractContextManager[Any]: ...

    def upsert_node(self, node: MemoryNode, *, return_clone: bool = True) -> tuple[MemoryNode, bool]: ...
    def upsert_edge(self, edge: MemoryEdge, *, return_clone: bool = True) -> tuple[MemoryEdge, bool]: ...
    def batch_upsert_nodes(self, nodes: Sequence[MemoryNode], *, return_clones: bool = True) -> list[tuple[MemoryNode, bool]]: ...
    def batch_upsert_edges(self, edges: Sequence[MemoryEdge], *, return_clones: bool = True) -> list[tuple[MemoryEdge, bool]]: ...
    def remove_node(self, node_id: str) -> bool: ...
    def remove_edge(self, edge_id: str) -> bool: ...
    def get_node(self, node_id: str, *, clone: bool = True) -> MemoryNode | None: ...
    def get_nodes(self, node_ids: Sequence[str]) -> list[MemoryNode]: ...
    def get_edge(self, edge_id: str, *, clone: bool = True) -> MemoryEdge | None: ...
    def get_node_by_key(self, type_: str, canonical_key: str) -> MemoryNode | None: ...
    def get_edge_by_pattern(self, from_id: str, to_id: str, type_: str) -> MemoryEdge | None: ...
    def get_edges(self, *, from_id: str | None = None, to_id: str | None = None, type_: str | Sequence[str] | None = None, limit: int = 1000, clone: bool = True) -> list[MemoryEdge]: ...
    def incident_edges(self, node_ids: Sequence[str], *, edge_types: set[str] | None = None, ignored_edge_types: set[str] | None = None, limit: int = 10000, clone: bool = True) -> list[MemoryEdge]: ...
    def neighbors(self, node_id: str, *, direction: str = "both", edge_types: set[str] | None = None, min_weight: float = 0.0, limit: int = 500) -> list[tuple[MemoryEdge, MemoryNode]]: ...
    def find_nodes_by_property(self, property_name: str, value: Any, *, type_: str | None = None, status: str | Sequence[str] | None = None, limit: int = 1000, clone: bool = True) -> list[MemoryNode]: ...
    def find_edges_by_property(self, property_name: str, value: Any, *, type_: str | None = None, limit: int = 1000, clone: bool = True) -> list[MemoryEdge]: ...
    def bounded_neighborhood(self, node_id: str, *, max_depth: int = 2, edge_types: set[str] | None = None, limit: int = 1000) -> tuple[list[MemoryNode], list[MemoryEdge]]: ...
    def archive_nodes_by_artifact(self, project_id: str, artifact_id: str, *, node_types: Sequence[str] | None = None) -> int: ...
    def update_node_metrics(self, node_id: str, **metrics: Any) -> MemoryNode | None: ...
    def persist_analysis_results(self, nodes: Sequence[MemoryNode], edges: Sequence[MemoryEdge]) -> dict[str, int]: ...
    def update_node_fields(self, node_id: str, **fields: Any) -> MemoryNode | None: ...
    def update_edge_fields(self, edge_id: str, **fields: Any) -> MemoryEdge | None: ...
    def all_nodes(self) -> list[MemoryNode]: ...
    def all_edges(self) -> list[MemoryEdge]: ...
    def find_nodes(self, *, type_: str | None = None, status: str | Sequence[str] | None = None, limit: int = 100, order_by: str = "salience", descending: bool = True) -> list[MemoryNode]: ...
    def count_nodes(self, *, node_types: set[str] | None = None, statuses: set[str] | None = None, project_id: str | None = None, include_global_project: bool = True) -> int: ...
    def count_edges(self, *, edge_types: set[str] | None = None, project_id: str | None = None, include_global_project: bool = True) -> int: ...
    def node_type_counts(self, *, statuses: set[str] | None = None, project_id: str | None = None, include_global_project: bool = True) -> dict[str, int]: ...
    def top_nodes_by_degree(self, *, limit: int = 100, node_types: set[str] | None = None, statuses: set[str] | None = None, exclude_types: set[str] | None = None, ignored_edge_types: set[str] | None = None, project_id: str | None = None, include_global_project: bool = True) -> list[tuple[MemoryNode, int, float]]: ...
    def lexical_search(self, text: str, *, top_k: int = 20, node_types: set[str] | None = None, include_archived: bool = False) -> list[tuple[MemoryNode, float]]: ...
    def degree(self, node_id: str, *, edge_types: set[str] | None = None) -> int: ...
    def record_usage_event(self, query_text: str, ranked_nodes: Sequence[dict[str, Any]]) -> None: ...
    def usage_for_node(self, node_id: str) -> dict[str, Any]: ...
    def log_operation(self, op_type: str, payload: dict[str, Any]) -> None: ...
    def export_json(self) -> dict[str, Any]: ...
